all:			NodeFile.class HeartBeat.class \
			Node.class Main.class

NodeFile.class:		NodeFile.java
			@javac NodeFile.java

HeartBeat.class:	HeartBeat.java
			@javac HeartBeat.java

Node.class:	Node.java
			@javac Node.java

Main.class:	Main.java
			@javac Main.java

clean:
			@rm -f *.class *~

